apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: medcattrainer-envs-env
  name: envs-env
data:
  CONCEPT_SEARCH_SERVICE_HOST: mct-solr
  CONCEPT_SEARCH_SERVICE_PORT: "8983"
  DEBUG: "True"
  ENV: non-prod
  LOAD_EXAMPLES: "1"
  MAX_DATASET_SIZE: "10000"
  MEDCAT_CONFIG_FILE: /home/configs/base.txt
  UNIQUE_DOC_NAMES_IN_DATASETS: "True"
