apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels: 
    io.kompose.service: mct-solr
  name: mct-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mct-solr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: mct-solr
    spec:
      containers:
        - image: "{{ .Values.solr.image }}:{{ .Values.solr.tag }}"
          name: mct-solr
          args:
            - -cloud
          ports:
            - containerPort: 8983
          resources:
            {{- toYaml .Values.medcattrainer.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/solr
              name: solr-data
          env: 
            - name: http_proxy
              value: ""
            - name: HTTP_PROXY
              value: ""
      restartPolicy: Always
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data
status: {}
