apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    io.kompose.service: mct-solr
  name: mct-solr
spec:
  ports:
    - name: http
      port: 8983
      targetPort: 8983
  selector:
    io.kompose.service: mct-solr
status:
  loadBalancer: {}
